resolvUrl
WildCodeSchool/2023-02-Orleans-Spe-P1-B pull request #25
Opened 2023-03-03 18:36 UTC by greegouze

2023-03-03 18:39 UTC, NefytZ submitted a review, later dismissed

2023-03-03 20:39 UTC, Ga-Mikael submitted a review, later dismissed

2023-03-04 11:10 UTC, YDrogen requested changes

2023-03-04 11:10 UTC, YDrogen commented on assets/JS/index.js
> +    linkNextPageButton.href = "../choiceHat/choice-hat.html";
```suggestion
    linkNextPageButton.href = "./choiceHat/choice-hat.html";
```

2023-03-04 11:10 UTC, YDrogen commented on passTest.html
> +        <img class="look-for-differences" src="../assets/images/finaldiff.png" alt="Trouver les differences">
```suggestion
        <img class="look-for-differences" src="./assets/images/finaldiff.png" alt="Trouver les differences">
```

2023-03-04 19:46 UTC, NefytZ approved these changes

2023-03-06 08:08 UTC, YDrogen approved these changes

2023-03-06 08:08 UTC, merged